//
// Created by three on 2025/4/25.
//

#ifndef PVPCS_HW_110KW_DATA_PROTOCOL_H
#define PVPCS_HW_110KW_DATA_PROTOCOL_H

#define PVPCS_HW_110KW_READ_DATA_INFOS_NUM 6
#define PVPCS_HW_110KW_WRITE_DATA_INFOS_NUM 2

#include "modbus_master_struct.h"

typedef enum
{
        R_PVPCS_HW_110KW_PMAX,
        R_PVPCS_HW_110KW_STATUS,
        R_PVPCS_HW_110KW_INPUT_POWER,
        R_PVPCS_HW_110KW_ACTIVE_POWER,
        R_PVPCS_HW_110KW_POWER_GENERATION,
        R_PVPCS_HW_110KW_ACTIVE_POWER_INFO,
} PVPCS_HW_110KW_READ_DATA_NAME_E;

typedef enum
{
        W_PVPCS_HW_110KW_ACTIVE_POWER_FIX_VALUE_SET,
        W_PVPCS_HW_110KW_ACTIVE_POWER_PERCENTAGE_SET,
} PVPCS_HW_110KW_WRITE_DATA_NAME_E;

extern ModbusMasterDataProtocol_T pvpcsHw110kwDataProtocol;

#endif   // PVPCS_HW_110KW_DATA_PROTOCOL_H
