//
// Created by three on 2025/4/25.
//

#ifndef PVPCS_SOFAR_50KW_DATA_PROTOCOL_H
#define PVPCS_SOFAR_50KW_DATA_PROTOCOL_H

#include "modbus_master_struct.h"

#define R_PVPCS_SOFAR_50KW_READ_DATA_INFOS_NUM 5
#define R_PVPCS_SOFAR_50KW_WRITE_DATA_INFOS_NUM 1

typedef enum
{
        R_PVPCS_SOFAR_50KW_STATUS,//0404
        R_PVPCS_SOFAR_50KW_ACTIVE_POWER,//0485 0.01kw
        R_PVPCS_SOFAR_50KW_INPUT_POWER,//05c4 0.1kw
        R_PVPCS_SOFAR_50KW_POWER_GENERATION,//0x684 ,4, 0.01kWh
        R_PVPCS_SOFAR_50KW_PMAX,//0x06ED,0.1kw
}PVPCS_SOFAR_50KW_READ_DATA_NAME_E;

typedef enum
{
        W_PVPCS_SOFAR_50KW_ACTIVE_POWER_PRECENTAGE_SET,
}PVPCS_SOFAR_50KW_WRITE_DATA_NAME_E;

extern ModbusMasterDataProtocol_T pvpcsSofar50kwDataProtocol;

#endif //PVPCS_SOFAR_50KW_DATA_PROTOCOL_H
